### ISSUE TITLE
path for patterns.svg in windows 10

### ISSUE THREAD

**Issue by dominiklenne** [zirafa/inkscape-hatch-patterns#1]
Hi,
maybe for people in order to save search time, you could mention the path to patterns.svg in windows 10:

C:\Program Files\Inkscape\share\patterns\patterns.svg

Also as a hint: one has to open the editor as administrator via - win - (editor name) - right click - open as administrator. 

(many thx, patterns work well in my inkscape!)

greetings

Dominik

**Comment by zirafa** [comment]
Thanks! I updated the README with that information.
