### ISSUE TITLE
Unable to edit patterns.svg

### ISSUE THREAD

**Issue by Alballm** [zirafa/inkscape-hatch-patterns#3]
I'm working with ubuntu 18.04 and when I try to edit the patterns.svg to paste the hatch patterns, the text editor warns me that I do not have the permission to change that file. How can the permission issue be fixed?

**Comment by zirafa** [comment]
What is the path to patterns.svg? I would first try opening the file from a path you have permissions such as your home directory, i.e.
``` 
cd ~
sudo nano ~/path/to/patterns.svg
```

**Comment by zirafa** [comment]
This should be resolved by #10
