### ISSUE TITLE
Alternate install method

### ISSUE THREAD

**Issue by passcod** [zirafa/inkscape-hatch-patterns#5]
To make the patterns available globally **without** butchering the built-in patterns file and without permission issues:

1. Rename `Defs.txt` to `hatch-patterns.svg`.
2. Insert this at the top:

```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Created with Inkscape (http://www.inkscape.org/) -->
<svg
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:xlink="http://www.w3.org/1999/xlink"
   width="475"
   height="1280"
   id="HatchPatterns"
   sodipodi:version="0.32">
  <title>Hatch Patterns</title>
  <defs
     id="defs4521">
```

3. Insert this at the bottom (maybe a new file with those modifications could be provided in the repo):

```svg
</defs>
</svg>
```

4. Open up your **user** inkscape config (on linux it's `~/.config/inkscape/`) and place the file in the `paint` folder.

5. Reload inkscape.

The hatches are available from the Object > Paint Servers menu under the name "Hatch Patterns" (as from the `<title>` in the code above).

**Comment by zirafa** [comment]
Thanks, feel free to open a PR. 

Is this for Inkscape 1.0? The instructions were for .92 so some things may have changed.

**Comment by passcod** [comment]
The path location might be only for 1.0 but I think the Paint Server thing has been there a while ---- On Mon, 30 Nov 2020 10:01:45 +1300  notifications@github.com  wrote ----
Thanks, feel free to open a PR.
Is this for Inkscape 1.0? The instructions were for .92 so some things may have changed.
